### ISSUE TITLE
Usage of the project.

### ISSUE THREAD

**Issue by Arrenign** [Kiarasht/Space-Station-Tracker#2]
Hi sir, Wonderful work.
Do I have permission to use this project with mild alterations in my own app?.

Thanks and regards,
Arren. @Kiarasht

**Comment by Kiarasht** [comment]
I have this under [Mozilla Public License 2.0](https://github.com/Kiarasht/Space-Station-Tracker/blob/master/LICENSE.txt) 
Let me know if this covers what you need.

**Comment by Arrenign** [comment]
Hi kiarasht,
I stared into the document license for about like 10 mins. It was like sitting inside the Apollo 11 seeing all those shiny buttons, not knowing what its for loll. Please pardon me I'll just tell you what I intent to use your source code for and could you please tell me if that would be okay according to the license,
1. Alteration of code.
2.Inclusion of new elements (here and there).
3.Changing of package name and uploading it on the google Playstore with a new design (i.e new colors, new logo, new pictures etc.)
4.And Running ads on them.

So will the above changes be okay with the license, please do enlighten me on this issue as I'm kinda new.

Thanks & regards,
Arren (Have a great day)

**Comment by Kiarasht** [comment]
Yes, it allows commercial purposes but needs to be open source and under the same license. 
There is an overview at the top of the page.

![licence](https://user-images.githubusercontent.com/6108985/39346173-a29c22d8-49a1-11e8-98fa-41454c949c4a.PNG)
