### ISSUE TITLE
App crashes when checking notification for flybys on api 22 and below.

### ISSUE THREAD

**Issue by Arrenign** [Kiarasht/Space-Station-Tracker#3]
Hi kiarasht the app crashes only in api below 22. It even happens in the play store app that you released.

Strangely the query is passed to this piece of code and crashes `@TargetApi(Build.VERSION_CODES.M)
        public void getLocationPermission() {
            requestPermissions(new String[]{android.Manifest.permission.ACCESS_FINE_LOCATION}, 1);
        }`

was wondering it shouldn't happen rite? cause its not targeting M versions and above while asking for permissions on api 22 and below. Could you please give me a solution.

**Comment by Kiarasht** [comment]
I can try and reproduce it, I know after extended period of time the background service might stop/crash but not right after checking it.

**Comment by Arrenign** [comment]
Yeah for some odd reason it happens only in api 22 and below. Android document says that fine location permissions are not considered to be a dangerous permission for api 22 and below and only requires us to ask permission for oreo and above. Like I said the stack trace showed that the app crashed in the asking permission part.
Anyway,
just found a weird fix to this or I assume a fix. Please check on this fix If you have the time,

Preferences.java - 
**Original**
`  public boolean isLocationPermissionGranted() {
            _return Build.VERSION.SDK_INT >= 23_ && mContext.checkSelfPermission(android.Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED;
        }`
**Changed too**
` public boolean isLocationPermissionGranted() {
            _return Build.VERSION.SDK_INT <= Build.VERSION_CODES.M ||_ mContext.checkSelfPermission(android.Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED;
        }`

and No crash on Api-22 and below || Still asks for fine location permission in 23 and above.

**Comment by Arrenign** [comment]
Oh yeah that former problem I mentioned is fixed by the snippet change I mentioned above but like you said the alert service kinda stops after a certain period of time returning sometimes with this error "java.lang.indexoutofboundsexception: invalid index 0, size is 0 dates =0". Have any ideas ??

**Comment by Kiarasht** [comment]
Hmm looks like I'm just not checking for if service hasn't returned any dates. Do you have the whole stacktrace?

**Comment by Arrenign** [comment]
Yeah sure
`Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
              at java.util.ArrayList.get(ArrayList.java:308)
                   at com.restart.spacestationtracker.services.Alert$2.run(Alert.java:118)
                       at java.util.Timer$TimerImpl.run(Timer.java:284)`

here you go kiarasht. ' **&& (dates == null || dates.get(0) == null); ++i)** ' <-- this is the line it tells me that its getting a zero. 
The thing is that you have to wait an unknown amount of time to reproduce the issue and sometimes it doesn't even happen till 24hrs have passed sometimes it happens after a few minutes.

**Comment by Kiarasht** [comment]
Yeah some of my logics are old as hell and haven't touched them in a while. I can look at this over the weekend when I'm not at work. If you think you solved the other crash issue, feel free to open a pr for it.

**Comment by Arrenign** [comment]
Yeah, sure ...

**Comment by Kiarasht** [comment]
The `IndexOutOfBoundsException` should now be fixed.

**Comment by Arrenign** [comment]
Thanks Kiarasht So far no error and am sure its fixed. Great work

**Comment by Arrenign** [comment]
Yep its fixed. tested it in a 24 Hrs time frame and no errors produced and the notifications are also fine, being displayed.Thanks. I'll close this thread.
